### PR TITLE
updated to create-react-app 2, fixing security issues

### PR DESCRIPTION
**Pull request by pahund**
Hi Oleg, not sure if this repo is still needed, perhaps can be deleted? Otherwise, here's a PR that fixes major security issues by upgrading create-react-app to latest and greatest.

### CODE REVIEW

**Comment by kof** [comment]
I don't know if its still used internally, form my side feel free to just remove it if they don't need it.

**Comment by kof** [comment]
I just disabled alerts.

**Comment by toser** [comment]
I would like to keep it for now. I'll bring it up in our next sync meeting.

**Review by toser — APPROVED** [review]
Thx for updating.

**Pull request merged**
